support for gnustep base >= 1.29.0
Alinto/sope pull request #66
Opened 2023-11-07 18:31 UTC by binary-jam

some enum constants in gnustep base libs have changed with 1.29.0, which breaks compatibility with sope.
changing commit is: https://github.com/gnustep/libs-base/commit/fe2f41c7f19f19bf8b5100a2124e815d92d784d1

only two enum constants in NGMimeType.m are affected, both of which under a section commented with "some unsupported, but known encoding". from gnustep base 1.29.0 on there are multiple enum constants for GB2312 encoding. after some research i decided to go for NSHZ_GB_2312StringEncoding, because it references the 7-bit HZ-encoding used in mailing.

2024-01-21 02:46 UTC, SlavekB requested changes
You need to fix a typo – see the comments below.
After fixing the version number in the test, build was successful – both on older distributions and also for the upcoming Ubuntu 24.04 (Noble), where the gnustep-base is 1.29.0.

2024-01-21 02:46 UTC, SlavekB commented on sope-mime/NGMime/NGMimeType.m
> +#if ((GNUSTEP_BASE_MAJOR_VERSION >= 1) && (GNUSTEP_BASE_MINOR_VERSION >= 19) && (GNUSTEP_BASE_SUBMINOR_VERSION >= 0))
There is a typo in  `GNUSTEP_BASE_MINOR_VERSION` – it should be 29, not 19.
This will cause FTBFS on older versions.

2024-01-21 02:46 UTC, SlavekB commented on sope-mime/NGMime/NGMimeType.m
> +#if ((GNUSTEP_BASE_MAJOR_VERSION >= 1) && (GNUSTEP_BASE_MINOR_VERSION >= 19) && (GNUSTEP_BASE_SUBMINOR_VERSION >= 0))
There is a typo in  `GNUSTEP_BASE_MINOR_VERSION` – it should be 29, not 19.
This will cause FTBFS on older versions.

2024-01-21 02:55 UTC, SlavekB requested changes
I realized one more deficiency: the test in this form will not be correct as soon as `GNUSTEP_BASE_MAJOR_VERSION` will be raised to 2.
There you will need to use:
```
#if ((GNUSTEP_BASE_MAJOR_VERSION > 1) || ((GNUSTEP_BASE_MAJOR_VERSION == 1) && (GNUSTEP_BASE_MINOR_VERSION >= 29)))
```

2024-01-21 20:47 UTC, WoodySlum commented on sope-mime/NGMime/NGMimeType.m
> +#if ((GNUSTEP_BASE_MAJOR_VERSION >= 1) && (GNUSTEP_BASE_MINOR_VERSION >= 19) && (GNUSTEP_BASE_SUBMINOR_VERSION >= 0))
Hi, I think this is not correct, I suggest this :

```
#define C_GNUSTEP_VERSION    (GNUSTEP_BASE_MAJOR_VERSION * 1000000) + (GNUSTEP_BASE_MINOR_VERSION * 1000) + GNUSTEP_BASE_SUBMINOR_VERSION
#if C_GNUSTEP_VERSION > 1029000
```

2024-01-28 18:54 UTC, binary-jam commented
Oh wow. I'm terribly sorry you had to waste your time on that mistake.
I've opted for WoodySlum's proposal, because it seems to be the most readable to me.

Changes are also tested on my system with gnustep-base 1.29.0 and it compiles just fine.

2024-01-29 08:21 UTC, merged